api_name: []
items:
- _type: class
  children: []
  class: cntk.train.training_session.CheckpointConfig
  fullName: cntk.train.training_session.CheckpointConfig
  inheritance:
  - - cntk.cntk_py.CheckpointConfig
    - builtins.object
  module: cntk.train.training_session
  name: CheckpointConfig
  references: []
  source:
    id: CheckpointConfig
    path: cntk/train/training_session.py
    remote:
      branch: master
      path: cntk/train/training_session.py
      repo: null
    startLine: 16
  syntax:
    exceptions: []
    parameters:
    - description: checkpoint file name.
      id: preserve_all
      type: bool
    - description: checkpoint frequency in samples. If 0, no checkpointing takes place.
        If `sys.maxsize`, a single checkpoint is taken at the end of the training.
      id: frequency
      type: int
    - description: saves all checkpoints, using `filename` as prefix and checkpoint
        index as a suffix.
      id: restore
      type: bool
    - description: flag, indicating whether to restore from available checkpoint before
        the start of the training
      id: filename
      type: str
    returntype: ''
    returnvalue: ''
    summary: 'Bases: `cntk.cntk_py.CheckpointConfig`

      A checkpoint configuration for the training session.'
    variables: []
  type: Class
  uid: cntk.train.training_session.CheckpointConfig
