#YamlMime:PythonReference
api_name: []
items:
- _type: class
  children: []
  class: cntk.io.StreamConfiguration
  fullName: cntk.io.StreamConfiguration
  inheritance:
  - inheritance:
    - type: builtins.object
    type: cntk.cntk_py.StreamConfiguration
  langs:
  - python
  module: cntk.io
  name: StreamConfiguration
  source:
    id: StreamConfiguration
    path: cntk/io/__init__.py
    remote:
      branch: master
      path: cntk/io/__init__.py
      repo: https://github.com/Microsoft/CNTK
    startLine: 478
  summary: 'Bases: `cntk.cntk_py.StreamConfiguration`

    Configuration of a stream in a text format reader.'
  syntax:
    content: StreamConfiguration(self, name, dim, is_sparse=False, stream_alias="")
    parameters:
    - description: name of this stream
      id: name
      type:
      - str
    - description: dimensions of this stream. A text format reader reads data as flat
        arrays. If you need different shapes you can `reshape()` it later.
      id: dim
      type:
      - int
    - description: whether the provided data is sparse (*False* by default)
      id: is_sparse
      type:
      - bool, defaults to False
    - description: name of the stream in the file
      id: stream_alias
      type:
      - str, defaults to ''
  type: Class
  uid: cntk.io.StreamConfiguration
references: []
