api_name: []
items:
- _type: class
  children: []
  class: cntk.train.training_session.CrossValidationConfig
  fullName: cntk.train.training_session.CrossValidationConfig
  inheritance:
  - - cntk.cntk_py.CrossValidationConfig
    - builtins.object
  module: cntk.train.training_session
  name: CrossValidationConfig
  references: []
  source:
    id: CrossValidationConfig
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/train/training_session.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/train/training_session.py
      repo: null
    startLine: 55
  syntax:
    exceptions: []
    parameters:
    - description: minibatch source used for cross validation
      id: source
      type: MinibatchSource
    - description: frequency in samples for cross validation If `sys.maxsize`, a single
        cross validation is performed at the end of training.
      id: callback
      type: func (index, avarage_error, cv_num_samples, cv_num_minibatches)
    - description: minibatch schedule for cross validation
      id: frequency
      type: int
    - description: Callback that will be called with frequency which can implement
        custom cross validation logic, returns False if training should be stopped.
      id: schedule
      type: minibatch_size_schedule
    returntype: ''
    returnvalue: ''
    summary: 'Bases: `cntk.cntk_py.CrossValidationConfig`

      A cross validation configuration for the training session.'
    variables: []
  type: Class
  uid: cntk.train.training_session.CrossValidationConfig
