#YamlMime:PythonReference
api_name: []
items:
- _type: class
  children: []
  class: cntk.train.training_session.CheckpointConfig
  fullName: cntk.train.training_session.CheckpointConfig
  inheritance:
  - inheritance:
    - type: builtins.object
    type: cntk.cntk_py.CheckpointConfig
  langs:
  - python
  module: cntk.train.training_session
  name: CheckpointConfig
  source:
    id: CheckpointConfig
    path: cntk/train/training_session.py
    remote:
      branch: master
      path: cntk/train/training_session.py
      repo: https://github.com/Microsoft/CNTK
    startLine: 16
  summary: 'Bases: `cntk.cntk_py.CheckpointConfig`

    A checkpoint configuration for the training session.'
  syntax:
    content: CheckpointConfig(self, filename, frequency=None, restore=True, preserve_all=False)
    parameters:
    - description: checkpoint file name.
      id: filename
      type:
      - str
    - description: checkpoint frequency in samples. If 0, no checkpointing takes place.
        If `sys.maxsize`, a single checkpoint is taken at the end of the training.
      id: frequency
      type:
      - int
    - description: saves all checkpoints, using `filename` as prefix and checkpoint
        index as a suffix.
      id: preserve_all
      type:
      - bool
    - description: flag, indicating whether to restore from available checkpoint before
        the start of the training
      id: restore
      type:
      - bool
  type: Class
  uid: cntk.train.training_session.CheckpointConfig
references: []
